### ISSUE TITLE
C-style loop and ++ operator are deprecated in Swift 2.2

### ISSUE THREAD

**Issue by mac-cain13** [Q42/Q42.ImagePreview.swift#7]
Would be nice to refactor this loop so it doesn't warn anymore with Swift 2.2 and won't break with Swift 3: https://github.com/Q42/Q42.ImagePreview.swift/blob/develop/src/ImagePreview/UIImage%2BBlur.swift#L151-L153

**Comment by timvansteenis** [comment]
Thanks for making me aware ;)

https://github.com/Q42/Q42.ImagePreview.swift/pull/8
